name: UnityTestRunner

on:
  pull_request:
    types: [opened, synchronize]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: UnityTestRunnerBuild
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        id: unity-test-runner
        with:
          unityVersion: 2020.1.0b15
          artifactsPath: all-artifacts
          
      - uses: actions/upload-artifact@master
        with:
          name: test_results
          path: ${{ steps.unity-test-runner.outputs.artifactsPath }}

      # Output 
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: Build
      #    path: build
